---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: Ansible delete file
    find:
      paths: ./var_file/
      patterns: "*.yaml"
    register: files_to_delete
    no_log: True

  - name: Ansible remove existing var file
    file:
      path: "{{ item.path }}"
      state: absent
    with_items: "{{ files_to_delete.files }}"
    no_log: True

  - name: Run a script
    script: ./scripts/start_job.sh
    register: test
    no_log: True
