---
- hosts: all
  connection: local
  gather_facts: no
  tasks:
  - name: Run a script
    script: start_automation_task.sh
    register: test
  - name: print script result
    debug:
      msg: "{{ test }}" 
